apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: checker
  namespace: monitor-page
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: checker
    spec:
      containers:
      - name: master
        image: registry.example.url/d0ku/monitor_page_checker
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: secret-sendgrid
              key: api-key
        - name: URL_TO_CHECK
          value: http://prs.pwr.edu.pl
        - name: MAIL_RECIPIENT
          value: darthtyranus666666@gmail.com
        - name: SLEEP_TIME
          value: "1200"
        - name: MAKE_SCREENSHOTS
          value: "1"
        - name: STARTED_MAIL
          value: "1"
        - name: SCREENSHOT_API
          value: "http://screenshoter.monitor-page.svc.cluster.local:8080"
        - name: SENDER_API
          value: "http://sender.monitor-page.svc.cluster.local:8080"
      imagePullSecrets:
      - name: regcred
