kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: monitor-page
 name: role-apps-management
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: role-apps-management-binding
 namespace: monitor-page
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitor-page
roleRef:
 kind: Role
 name: role-apps-management
 apiGroup: rbac.authorization.k8s.io
