apiVersion: v1
kind: Service
metadata:
  name:  {{ include "monitor_page.fullname" . }}-comparator
  namespace: {{ .Values.comparator.namespace }}
  labels:
    app: comparator
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.comparator.service.port }}
    targetPort: 8080
  selector:
    app: comparator
