{{- if ne .Values.db.replicaCount 0.0 }}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Values.db.teamId }}-{{ include "monitor_page.fullname" . }}-db
spec:
  teamId: {{ .Values.db.teamId }}-{{ include "monitor_page.fullname" . }}
  volume:
    size: 1Gi
    storageClass: "{{ .Values.db.storageClass }}"
  numberOfInstances: {{ .Values.db.replicaCount }}
  users:
    {{ .Values.db.dbOwner }}:
    - superuser
    - createdb
  databases:
    monitor: "{{ .Values.db.dbOwner }}"
  postgresql:
    version: "11"
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
              - amd64
{{- end }}
