apiVersion: v1
kind: Service
metadata:
  name:  {{ printf "%s-%s" (include "monitor-page.fullname" .) .Values.front.service.name }}
  labels:
    app: front
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.front.service.port }}
    targetPort: 80
  selector:
    app: front
