apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitor_page.fullname" . }}-manager
  namespace: {{ .Values.manager.namespace }}
spec:
  selector:
    matchLabels:
      {{- include "monitor_page.selectorLabels" . | nindent 6 }}
      app: manager
  {{- if not .Values.manager.autoscaling.enabled }}
  replicas: {{ .Values.manager.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "monitor_page.selectorLabels" . | nindent 8 }}
        app: manager
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.manager.securityContext | nindent 12 }}
          image: "{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.manager.resources | nindent 12 }}
          env:
          - name: APP_URL
            value: "{{ .Values.manager.env.APP_URL | default (printf "https://api.%s" .Values.baseUrl) }}"
          - name: CHECKER_IMAGE
            value: "{{ .Values.manager.env.CHECKER_IMAGE | default (printf "%s/d0ku/monitor_page_checker:%s" .Values.baseRegistry .Chart.AppVersion) }}"
          - name: CHECKER_NAMESPACE
            value: "{{ .Values.namespace }}"
          - name: FRONT_URL
            value: "{{ .Values.manager.env.FRONT_URL | default (printf "https://%s" .Values.baseUrl) }}"
          - name: ALLOWED_ORIGIN
            value: "{{ .Values.manager.env.ALLOWED_ORIGIN }}"
            # TODO: something has to be done about this entry
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: "{{ (printf "%s-secret-jwt" (include "monitor_page.fullname" .)) }}"
                key: jwt-secret
          - name: SENDER_API
            value: "{{ (printf "http://sender.%s.svc.cluster.local:%.0f" (.Values.sender.namespace | default .Values.namespace) .Values.sender.service.port) }}"
          - name: DATABASE_TYPE
            value: "{{ .Values.db.dbType }}"
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: "{{ (printf "%s.%s-db.credentials" .Values.db.dbOwner (include "monitor_page.fullname" .))}}"
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ (printf "%s.%s-db.credentials" .Values.db.dbOwner (include "monitor_page.fullname" .))}}"
                key: password
          - name: DATABASE_PORT
            value: "{{ .Values.db.dbPort }}"
          - name: DATABASE_HOST
            value: "{{ (printf "http://%s-db.%s.svc.cluster.local:8080"  (include "monitor_page.fullname" .) (.Values.db.namespace | default .Values.namespace)) }}"
          - name: DATABASE_DB_NAME
            value: "{{ .Values.db.dbName }}"
          - name: SCREENSHOT_SERVICE
            value: "{{ include "monitor_page.fullname" . }}-screenshoter"
          - name: SENDER_SERVICE
            value: "{{ include "monitor_page.fullname" . }}-sender"
          - name: COMPARATOR_SERVICE
            value: "{{ include "monitor_page.fullname" . }}-comparator"
          - name: SCREENSHOT_API_PORT
            value: "{{ .Values.screenshoter.service.port }}"
          - name: SENDER_API_PORT
            value: "{{ .Values.sender.service.port }}"
          - name: COMPARATOR_API_PORT
            value: "{{ .Values.comparator.service.port }}"

      {{- with .Values.manager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.manager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.manager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
