apiVersion: v1
kind: Service
metadata:
  name:  {{ printf "%s-%s" (include "monitor_page.fullname" .) .Values.manager.service.name }}
  labels:
    app: manager
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.manager.service.port }}
    targetPort: 8000
  selector:
    app: manager
