apiVersion: v1
kind: Service
metadata:
  name:  {{ include "monitor_page.fullname" . }}-manager
  namespace: {{ .Values.manager.namespace }}
  labels:
    app: manager
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.manager.service.port }}
    targetPort: 8000
  selector:
    app: manager
