apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitor-page.fullname" . }}-screenshoter
spec:
  selector:
    matchLabels:
      {{- include "monitor-page.selectorLabels" . | nindent 6 }}
      app: screenshoter
  {{- if not .Values.screenshoter.autoscaling.enabled }}
  replicas: {{ .Values.screenshoter.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "monitor-page.selectorLabels" . | nindent 8 }}
        app: screenshoter
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.screenshoter.securityContext | nindent 12 }}
          image: "{{ .Values.manager.image.repository | default (printf "%s/d0ku/monitor-page_screenshoter" .Values.baseRegistry) }}:{{ .Values.manager.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.screenshoter.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/live
              port: http
          readinessProbe:
            httpGet:
              path: /v1/ready
              port: http
          resources:
            {{- toYaml .Values.screenshoter.resources | nindent 12 }}
      {{- with .Values.screenshoter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.screenshoter.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.screenshoter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
