apiVersion: v1
kind: Service
metadata:
  name:  {{ include "monitor-page.fullname" . }}-screenshoter
  labels:
    app: screenshoter
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.screenshoter.service.port }}
    targetPort: 8080
  selector:
    app: screenshoter
