apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitor_page.fullname" . }}-secret-jwt
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  jwt-secret: {{ .Values.jwtSecret | b64enc }}
