apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitor_page.fullname" . }}-secret-sendgrid
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  api-key: {{ .Values.sendgridAPIKey | b64enc }}
