apiVersion: v1
kind: Service
metadata:
  name:  {{ include "monitor-page.fullname" . }}-sender
  labels:
    app: sender
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.sender.service.port }}
    targetPort: 8080
  selector:
    app: sender
