name: helm-publish
on:
  workflow_dispatch:
    inputs:
      repoRef:
        required: true
        default: 'master'
jobs:
  chart-publish:
    runs-on: ubuntu-latest
    needs: docker-publish
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.repoRef }}

      -
        name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4

      -
        name: Build Helm chart
        run: |
          cd k8s/monitor-page
          make
          helm package ./

      -
        name: Upload the Helm chart
        uses: actions/upload-artifact@v2
        with:
          name: monitor-page-chart
          path: k8s/monitor-page/*.tgz
